-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_SIZE-size_of_colony AS YEAR_DEV, ID
FROM ecoli_data AS A
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS BORN_YEAR, MAX(size_of_colony) AS MAX_SIZE
    FROM ecoli_data
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS B ON YEAR(A.DIFFERENTIATION_DATE) = B.BORN_YEAR
ORDER BY YEAR, YEAR_DEV